# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
commands:
  print_pipeline_id:
    description: "Print pipeline ID"
    parameters:
      id:
        type: string
        default: "None"
    steps:
      - run: echo << paramenters.id >>

jobs:

  print_pipeline:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - print_pipeline_id:
          id: ${CIRCLE_WORKFLOW_ID}

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - print_pipeline
